# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

#stages:
#- test
#sast:
 # stage: test
#include:`
#- template: Security/SAST.gitlab-ci.yml

#image: maven:3.8.4-openjdk-11-slim
stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  testngTest: "testSuites/01-sign-in-successfull.xml"

before_script:
  - sudo apt-get update -qy
  - sudo apt-get install -y maven

test:
  stage: test
  image: selenium/standalone-chrome:latest
  script:
    #- mvn clean test -DsuiteXmlFile=testSuites/01-sign-in-successfull.xml
    #- echo "TestNG Test Suite: ${testngTest}"
    - mvn clean test -DsuiteXmlFile=${testngTest}


































