# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

#stages:
#- test
#sast:
 # stage: test
#include:
#- template: Security/SAST.gitlab-ci.yml

stages:
  - test

variables:
  SUITE_1_PATH: "testSuites/01-sign-in-successful.xml"
  # SUITE_2_PATH: "testSuites/09-Create_Preparation.xml"
  # Add more suites as needed

testSuites:
  stage: test
  script:
    - chmod +x mvnw
    - ./mvnw test -Dsurefire.suiteXmlFiles=${SUITE_1_PATH} #,${SUITE_2_PATH}
    # Add more suites using a comma-separated list

  after_script:
    - mvn clean verify  # Assuming you want to clean and verify the project after tests
    - mvn dependency:purge-local-repository

  artifacts:
    paths:
      - target/           # Assuming this is where your build artifacts are generated
      - .m2/repository/   # Include Maven repository if needed
    expire_in: 1 week     # Adjust as needed based on your retention requirements

  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"  # Specify the Maven repository location
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"