name: 02 Sign In and Create Preapartion Suite

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the parameter'
        required: true

jobs:
  testSuites:
    runs-on: ubuntu-latest

    env:
      SUITE_1_PATH: testSuites/PreparationSuites/02-sign-in-addNewPreparationVIQ7.xml
      # SUITE_2_PATH: testSuites/09-Create_Preparation.xml

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"
          
      - name: Set execute permissions for mvnw
        run: chmod +x mvnw

      - name: Run TestNG Suites
        run: mvn test -Dsurefire.suiteXmlFiles=${SUITE_1_PATH}

      - name: Clear Maven Cache
        run: rm -rf ~/.m2/repository

      - name: Debug Information
        run: |
          echo "Current Directory: $(pwd)"
          java -version
          mvn -version
          ls -la
